version:  '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "assets_service_db_dev"
  confsvr:
    extends:
      file: ../common/docker-compose.yml
      service: confsvr
  assets-service:
      image: tofikmussa/assets-service:assignment2.1
      ports:
        - "8081:8081"
      environment:
        PROFILE: "dev"
        CONFIGSERVER_URI: "http://confsvr:8888"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"