eureka:
  instance:
    preferIpAddress: true
    ip-address: 192.168.99.100
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: companyChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: 192.168.99.100
  zipkin:
    base-url: http://192.168.99.100:9411
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://192.168.99.100:8084/auth/user

