server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tmussa1/config-server-repo/
          searchPaths: assets-service, company-service, zuul-service, specialroutes-service, authentication-service
          ignore-local-ssh-settings: true
      discovery:
        enabled: true
eureka:
  instance:
    preferIpAddress: true
    ip-address: 192.168.99.100
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
         